### PR TITLE
Update Zotero to 5.0.66

### PR DESCRIPTION
**Pull request by kiview**
Just a version update.

### CODE REVIEW

**Comment by ykgmfq** [comment]
Cloud you please add a new line for the current release? That way the release history is preserved.

**Comment by kiview** [comment]
@ykgmfq Ah I see, this wasn't done in prior updates?

**Comment by ykgmfq** [comment]
That's true. The person doing the change probably was not aware that the release section is a list.

**Comment by felipehw** [comment]
When updating to a new version, use the `build.sh`.
The `build.sh` updates things like sha512 and release version without any hassle.

**Comment by kiview** [comment]
@felipehw I wasn't aware of this, thanks for the hint, I will keep this in mind next time :slightly_smiling_face:

**Comment by felipehw** [comment]
@kiview, no problem! 🍺

**Pull request closed without merging**
